### ISSUE TITLE
Проблемы с ТТСом

### ISSUE THREAD

**Issue by dj-34** [ss220club/WyccerraBay220#10]
### Description of issue

- [x] ТТС слышно когда спишь
- [x] ТТС некорректно озвучивает языки которые игрок не понимает
- [x] Нет поочередности обработки сообщений (все воспроизводится сразу)
- [x] Кнопка выбора голоса ТТС находится повсюду в префах. Засунуть бы ее куда-нибудь в одно место (очко)...
- [x] Нет санитайза ударения (+)

![image](https://github.com/ss220club/WyccerraBay220/assets/20109643/9a003050-06f1-4588-a4ff-223c577f214e)

**Comment by Furrior** [comment]
Ну раз отвязались от апстрима, могу нормально сделать теперь все
