### ISSUE TITLE
Сброс положения пиксельфишта

### ISSUE THREAD

**Issue by BR54FF** [ss220club/WyccerraBay220#151]
### BYOND Version

515.1630

### Описание проблемы

Положение возвращается в изначальное после взаимодействия с персонажем в хелп интенте

### Что должно было произойти?

Персонаж должен был остаться в том же положении

### Что случилось вместо этого?

Персонаж сдвинулся в изначальное положение

### Почему это плохо/Какие последствия?

Нуууу эээ плохо. 

### Шаги для повторения проблемы.

Сдвинуться благодаря пиксельшифтингу, найти себе друга, который в хелп интенте обнимет тебя, обнаружить, что твой персонаж резко возвращается в исходную.

### Когда проблема началась?

Да видимо всегда была 

### Дополнительная информация

https://github.com/ss220club/WyccerraBay220/pull/85

**Comment by AyIong** [comment]
Защита от ЕРП, фича

**Comment by larentoun** [comment]
Фича

**Comment by Furrior** [comment]
> Защита от ЕРП, фича

Мы же вроде решили делать из сыра ерп билд как раз

**Comment by larentoun** [comment]
После вайтлиста добавить можно
