### ISSUE TITLE
Feature request. Clown and Mime are missing!

### ISSUE THREAD

**Issue by DedMaxim** [ss220club/WyccerraBay220#68]
### Описание проблемы

В названии уже описана вся суть проблемы. Ни клоуна, ни мима не существует. Мы в Станцию 13 играем или во что? Это является критической проблемой и имеет наивысший приоритет! Данный тикет следует исполнить в кратчайшие сроки! 

### Что должно было произойти?

Клоун роняет СБшников и ему пихают стан батон в задницу. Альтернативно, клоун докапывается до ГБС и становится обедом

### Что случилось вместо этого?

Всё тихо и спокойно

### Почему это плохо/Какие последствия?

Экипаж грустит, станбатоны грустят, ГБС ходят голодные

### Шаги для повторения проблемы.

Зайти на сервер, открыть список возможных ролей и разочароваться

### Когда проблема началась?

Всегда

### Дополнительная информация

Ситуация критическая, господа! Я не уверен, сколько мы ещё так протянем!

**Comment by Furrior** [comment]
Для этого есть роль актера. Если речь не только о наличии роли, а еще и о каком то механе и тп, то это уже совершенно другой разговор.
